Fix typo in name of CliffordPushThroughMeasures pass
CQCL/tket pull request #1532
Opened 2024-08-14 11:21 UTC by isobelhooper

# Description

This PR fixes a typo in the JSON `name` field for the CliffordPushThroughMeasures pass. The pass is correctly named in the Python bindings, but the typo shows up in the output of `.to_dict()` for the generated compiler pass.

This pass name isn't used in any tests (or output in the API docs, I think), so no test or docs changes are needed.

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

2024-08-14 11:38 UTC, sjdilkes submitted a review, later dismissed

2024-09-17 11:24 UTC, cqc-alec commented
Hi @isobelhooper , when you make any change to the tket source you have to bump the tket patch version number in `tket/conanfile.py` and correspondingly the required version in `pytket/conanfile.py`. This is why the CI is failing.

2024-09-17 13:35 UTC, isobelhooper commented
> Hi @isobelhooper , when you make any change to the tket source you have to bump the tket patch version number in `tket/conanfile.py` and correspondingly the required version in `pytket/conanfile.py`. This is why the CI is failing.

Thank you for this - have now made those changes in the commit as well!

2024-09-17 14:05 UTC, cqc-alec commented
Ah, looks like homebrew have removed clang-format 18 so the formatting check is failing. I'll fix this in a separate PR...

2024-09-19 08:41 UTC, cqc-alec requested changes
Version needs bumping again.

2024-09-19 08:41 UTC, cqc-alec commented on pytket/conanfile.py
> +        self.requires("tket/1.3.25@tket/stable")
```suggestion
        self.requires("tket/1.3.26@tket/stable")
```

2024-09-19 08:41 UTC, cqc-alec commented on tket/conanfile.py
> +    version = "1.3.25"
```suggestion
    version = "1.3.26"
```

2024-09-19 09:41 UTC, cqc-alec approved these changes

2024-09-19 09:41 UTC, merged