Feature/reorder multi qubit gates
CQCL/tket pull request #157
Opened 2021-12-17 10:26 UTC by yao-cqc

2022-01-04 16:36 UTC, sjdilkes requested changes
All readable and neat and well tested - just a few smallish things.

2022-01-07 16:24 UTC, yao-cqc commented on tket/src/Mapping/MultiGateReorder.cpp
> +Vertex get_input_from_vertex_edge(
I'm not sure how easy is it to update this information. Especially when gates are added during routing.

2022-01-07 16:27 UTC, yao-cqc commented on tket/src/Mapping/MultiGateReorder.cpp
> +      this->mapping_frontier_->get_frontier_subcircuit(UINT_MAX, UINT_MAX);
I added the parameters and set the default to UINT_MAXs. How do you feel about setting the default to UINT_MAX? The procedure isn't that expensive though.

2022-01-11 11:27 UTC, sjdilkes commented on tket/src/Mapping/MultiGateReorder.cpp
> +      this->mapping_frontier_->get_frontier_subcircuit(UINT_MAX, UINT_MAX);
The procedure isn't expensive, but it is likely being run many times through a full route, meaning making a subcircuit of the remaining Circuit each time will likely add up. I'd set the default lower for now (say 10) and we can work out a better set of default parameters later.

2022-01-11 12:08 UTC, sjdilkes commented on tket/src/Mapping/MultiGateReorder.cpp
> +Vertex get_input_from_vertex_edge(
Is it possible to at least traverse the DAG back to the MappingFrontier edges?

2022-01-11 12:14 UTC, sjdilkes requested changes
A continuation of prior conversation.

2022-01-17 15:54 UTC, sjdilkes requested changes
All looking good, though one final thing which I missed the other day - there are no  tests for MultiGateReorderRoutingMethod. I appreciate the functionality is tested already, but please could you add a simple couple of test cases for construction and calling methods, mainly for test coverage upkeep.

2022-01-18 15:26 UTC, yao-cqc commented
I refactored some methods so they can be reused by`MultiGateReorderRoutingMethod::check_method`.

2022-01-18 15:28 UTC, sjdilkes approved these changes
Nice!

2022-01-18 15:31 UTC, merged