WIP on ClExprOp.
CQCL/tket pull request #1628
Opened 2024-10-21 11:10 UTC by cqc-alec

# Description

Please summarise the changes.

# Related issues

Please mention any github issues addressed by this PR.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

2024-10-22 14:12 UTC, sjdilkes requested changes
I've only left a couple of comments - looks nice and clean. Could it be worth adding tests covering some of the strange behaviour from `ClassicalExpBox`, such as having classical expressions in `CircBox` that are copied, or python circuits that have classical expressions added, the units relabelled and then converted to qasm to confirm that the expressions are as desired?

2024-10-22 14:21 UTC, cqc-alec commented on tket/include/tket/Ops/ClExpr.hpp
> +// TODO Use X or list macros to reduce boilerplate.
Not really a concern, but the code could be made more compact; I'm happy to leave this for a future PR though.

2024-10-22 14:22 UTC, cqc-alec commented
> I've only left a couple of comments - looks nice and clean. Could it be worth adding tests covering some of the strange behaviour from `ClassicalExpBox`, such as having classical expressions in `CircBox` that are copied, or python circuits that have classical expressions added, the units relabelled and then converted to qasm to confirm that the expressions are as desired?

Good idea, I'll add some such tests.

2024-10-23 08:34 UTC, sjdilkes commented on tket/include/tket/Ops/ClExpr.hpp
> +   * @param bit_posn Map from identifiers of bit variables to bit positions
Thanks!

2024-10-23 08:35 UTC, sjdilkes commented on tket/include/tket/Ops/ClExpr.hpp
> +  unsigned i;  /// Identifier for the variable within the expression
Sounds good, thanks.

2024-10-23 08:49 UTC, sjdilkes approved these changes
Exciting, LGTM! So I could submit jobs to `QuantinuumBackend` with `qasm` conversion and `ClExpr` now and it should work?

2024-10-23 09:11 UTC, cqc-alec commented
> Exciting, LGTM! So I could submit jobs to `QuantinuumBackend` with `qasm` conversion and `ClExpr` now and it should work?

Yes I believe that should work. Note that there is not yet a version of `DecomposeClassicalExp` that works with `ClExpr`, but that should not be needed in many cases.

2024-10-23 09:14 UTC, merged