Remove outdated Routing code from repository
CQCL/tket pull request #165
Opened 2022-01-07 14:29 UTC by sjdilkes

i.e. "RoutingV2".

src/Routing used to store files for Routing and Placement code. Placement code is now in a new directory (src/Placement) and unused Routing code is deleted. 

Code for verifying whether a circuit respects an architecture's connectivity constraints is moved to Utils.

`RoutingFrontier` renamed to `PlacementFrontier` and moved to Placement.hpp.

Redundant tests removed.

2022-01-10 08:28 UTC, cqc-alec requested changes
* The verification code shouldn't move into `Utils`: `Utils` is for low-level routines with few dependencies and sits at the bottom of the component's dependency graph, whereas this code depends on `Circuit` and `Architecture` so belongs higher up the stack. The dependencies between the source subdirectories should form a DAG; this change breaks that requirement.
* You've removed `test_Routing.cpp` from the list of test files built, without deleting the actual file. If we're not building it we should delete the file, but are you sure that all the tests in it are now covered elsewhere? I don't see many new tests being added here -- have they already been added on this branch?

2022-01-11 09:58 UTC, sjdilkes commented
> * The verification code shouldn't move into `Utils`: `Utils` is for low-level routines with few dependencies and sits at the bottom of the component's dependency graph, whereas this code depends on `Circuit` and `Architecture` so belongs higher up the stack. The dependencies between the source subdirectories should form a DAG; this change breaks that requirement.
> * You've removed `test_Routing.cpp` from the list of test files built, without deleting the actual file. If we're not building it we should delete the file, but are you sure that all the tests in it are now covered elsewhere? I don't see many new tests being added here -- have they already been added on this branch?

I've moved the Verification files to the Mapping sub directory.
Oops, have removed the file.
The tests in `test_Routing.cpp` should be now covered over `test_LexiRoute.cpp`, `test_LexicographicalComparison.cpp`, `test_MappingFrontier.cpp` and `test_MappingManager.cpp.` These are all already in the branch.

2022-01-11 10:23 UTC, sjdilkes commented on pytket/tests/mitigation_test.py
> +    mm.route_circuit(rbell, [LexiRouteRoutingMethod(50)])
No good reason apart from the direction the wind was blowing at that moment. I'll add a default to the python binder and make these instances use that.

2022-01-11 12:52 UTC, cqc-alec approved these changes

2022-01-11 14:23 UTC, merged