[draft] add ass to rv3.1
CQCL/tket pull request #254
Opened 2022-02-25 12:25 UTC by cqc-melf

2022-02-25 14:14 UTC, cqc-melf commented
This is my suggestion to add aas routing and labelling into rv3.1.

2022-02-25 14:55 UTC, cqc-melf commented
Take a look on https://github.com/CQCL/tket/pull/206 for the old PR.

2022-02-25 16:35 UTC, sjdilkes requested changes
Just the todo!

2022-02-25 16:35 UTC, sjdilkes commented on pytket/tests/circuit_test.py
> +    linear_transformation = np.array([[1, 0], [0, 1]])  # TODO, this is wrong
Check TODO?

2022-02-25 16:35 UTC, sjdilkes commented on pytket/tests/mapping_test.py
> +            AASRouteRoutingMethod(1),
I'm finding this pretty satisfying!!

2022-02-25 17:03 UTC, sjdilkes submitted a review, later dismissed

2022-02-28 17:08 UTC, sjdilkes requested changes
Just a few things

2022-02-28 17:08 UTC, sjdilkes commented on tket/src/Mapping/AASLabelling.cpp
> +/*bool AASLabellingMethod::check_method(
remove

2022-02-28 17:08 UTC, sjdilkes commented on tket/src/Mapping/AASRoute.cpp
> +/*bool AASRouteRoutingMethod::check_method(
remove

2022-02-28 17:39 UTC, cqc-melf commented on .github/workflows/build_and_test.yml
> +      - feature/RV3.1
done

2022-02-28 17:40 UTC, cqc-melf commented on tket/src/Mapping/AASLabelling.cpp
> +/*bool AASLabellingMethod::check_method(
done

2022-02-28 18:02 UTC, sjdilkes approved these changes
Nice

2022-02-28 19:32 UTC, merged