[TKET-1613] Remove Rebase<Target> methods to simplify API.
CQCL/tket pull request #257
Opened 2022-02-28 09:32 UTC by Roland-djee

Fixes [TKET-1613](https://cqc.atlassian.net/browse/TKET-1613?atlOrigin=eyJpIjoiMWU4NWJmMTZhNWM0NGNkOWEyNTIzYThkNzViNjA5MmYiLCJwIjoiaiJ9).

This PR addresses the removal of now obsolete `Rebase<Target>` methods in the Python API.

2022-02-28 13:26 UTC, cqc-alec commented on pytket/binders/passes.cpp
> -      "RebaseCustom", &gen_rebase_pass,
Do not remove this one!

2022-02-28 13:26 UTC, cqc-alec commented on pytket/binders/passes.cpp
> -  m.def("RebaseTket", &RebaseTket, "Converts all gates to CX and TK1.");
Do not remove this one!

2022-02-28 13:28 UTC, cqc-alec commented
The idea is to remove backend-specific rebase passes -- _not_ `RebaseTket` or `RebaseCustom` (which are used extensively).

2022-02-28 13:29 UTC, Roland-djee commented
> The idea is to remove backend-specific rebase passes -- _not_ `RebaseTket` or `RebaseCustom` (which are used extensively).

OK got that.

2022-02-28 15:40 UTC, Roland-djee commented
@ss2165 suggested to use `RebaseCustom` in place of `auto_rebase_pass`.

2022-02-28 17:16 UTC, cqc-alec commented
Could you please also remove `SquashHQS` (although not a rebase pass it makes sense to do it at the same time)?

2022-02-28 22:23 UTC, Roland-djee commented on pytket/binders/passes.cpp
> -  m.def("RebaseCirq", &RebaseCirq, "Converts all gates to CZ, PhasedX and Rz.");
Done.

2022-02-28 22:46 UTC, Roland-djee commented
> Could you please also remove `SquashHQS` (although not a rebase pass it makes sense to do it at the same time)?

In eb37a11.

2022-03-01 06:39 UTC, cqc-alec commented on pytket/binders/passes.cpp
> -  m.def("RebaseCirq", &RebaseCirq, "Converts all gates to CZ, PhasedX and Rz.");
Please make the change in this PR.

2022-03-01 07:43 UTC, cqc-alec commented on pytket/binders/passes.cpp
> -  m.def("RebaseCirq", &RebaseCirq, "Converts all gates to CZ, PhasedX and Rz.");
PS. Please include in the changelog a list of the API functions  removed.

2022-03-01 10:15 UTC, cqc-alec requested changes
Just a minor thing.

2022-03-01 10:15 UTC, cqc-alec commented on pytket/tests/predicates_test.py
>      # Share name with SquashCustom
This comment doesn't make sense any more.

2022-03-01 10:24 UTC, cqc-alec approved these changes

2022-03-01 11:35 UTC, merged