Add option to `Transforms.ThreeQubitSquash` to target TK2 gates
CQCL/tket pull request #439
Opened 2022-07-12 14:31 UTC by cqc-alec

The existing `three_qubit_synthesis()` method decomposes a unitary into at most 20 CX gates. I have added an analogous `three_qubit_tk_synthesis()` method that decomposes a unitary into at most 15 TK2 gates. (It may be possible to do better than this, but I don't know how. I simply took the existing steps based on the cosine--sine decomposition and modified them. I had hoped that it might be possible to use fewer gates in the `two_qubit_diag_adjoint_plex_tk()` and `two_qubit_modified_cossin_circ_tk()` subroutines, but numerical experiments suggest not.)

Decompose `Unitary3qBox` using this method.

Add an option to the `three_qubit_squash` transform (and its Python wrapper) to target TK2 instead of CX.

2022-07-14 11:07 UTC, lmondada requested changes
Looking good, only very minor things. I've added some comments about conjugating with reversible circuits to get fewer CX counts in some cases, but that was more a note to self. I will add an issue to be investigated later.

2022-07-14 11:07 UTC, lmondada commented on tket/src/Transformations/ThreeQubitSquash.cpp
> +      clifford_simp(false).apply(repl);
If we `squash_1qb_to_tk1` in the `TK2` case, would it not make sense to do it here too? I would also move out `three_qubit_synthesis(get_3q_unitary(circ))` from the if-else clause to highlight only the differences between the two OpTypes, but that's subjective taste.

2022-07-14 11:34 UTC, cqc-alec commented on pytket/binders/transform.cpp
> +          py::arg("target_2q_gate") = OpType::CX)
I'll change to `target_2qb_gate` throughout.

2022-07-15 09:21 UTC, lmondada approved these changes
Thank you!

2022-07-15 09:27 UTC, merged