Add TK2 option to `FullPeppholeOptimise`
CQCL/tket pull request #469
Opened 2022-08-03 13:52 UTC by cqc-alec

2022-08-03 14:44 UTC, lmondada requested changes
All good. I suggest adding `two_qubit_squash` after `clifford_simp` as I mentioned. This should take care of TK2 support in `clifford_simp`, so we won't need a separate PR.

2022-08-03 14:44 UTC, lmondada commented on tket/src/Transformations/OptimisationPass.cpp
> +          clifford_simp(allow_swaps) >> synthesise_tk() >>
This should take care of Cliffords properly: any `TK2` gate that was clifford and decomposed will be resynthesised after `clifford_simp`. Swaps should be swallowed within TK2s and be handled later.

```suggestion
          clifford_simp(false) >> two_qubit_squash(OpType::TK2) >> synthesise_tk() >>
```

2022-08-03 14:44 UTC, lmondada commented on tket/tests/test_CompilerPass.cpp
> +    CHECK(n_gates_noswaps_tk2 == n_tk2_noswaps_tk2 + n_tk1_noswaps_tk2);
Mmmm, yes that's true. I guess that in some circuits with specific structure, the gains in terms of `Rzz` gates might make the effort worth it.

Any chance that random circuits are particularly ill-suited?

2022-08-03 15:25 UTC, cqc-alec commented on tket/tests/test_CompilerPass.cpp
> +    CHECK(n_gates_noswaps_tk2 == n_tk2_noswaps_tk2 + n_tk1_noswaps_tk2);
> Any chance that random circuits are particularly ill-suited?

Yes, that is possible.

2022-08-04 09:01 UTC, lmondada approved these changes

2022-08-04 09:02 UTC, merged