[feature] Support classical control in `two_qubit_squash`
CQCL/tket pull request #471
Opened 2022-08-04 10:07 UTC by lmondada

2022-08-30 09:23 UTC, cqc-alec requested changes

2022-08-30 09:23 UTC, cqc-alec commented on tket/tests/test_TwoQubitCanonical.cpp
> +  GIVEN("A circuit with classical control (3)") {
```suggestion
  GIVEN("A circuit with classical control (4)") {
```

2022-09-03 10:28 UTC, lmondada commented on tket/src/Circuit/include/Circuit/CircUtils.hpp
> +using Condition = std::optional<std::pair<std::list<VertPort>, unsigned>>;
Didn't know! I replaced it with a typedef.

2022-09-03 10:29 UTC, lmondada commented on tket/src/Transformations/BasicOptimisation.cpp
> +  EdgeVec cin_edges, cout_edges;
Good spot, I've removed the duplicate.

2022-09-03 10:30 UTC, lmondada commented on tket/src/Transformations/BasicOptimisation.cpp
> +      // TODO: use Phase OpType when available
Yes, added.

2022-09-03 12:05 UTC, lmondada commented on tket/src/Transformations/BasicOptimisation.cpp
> +          OpType::U1, {2 * replacement.get_phase()},
Done.

2022-09-03 12:06 UTC, lmondada commented on tket/tests/test_TwoQubitCanonical.cpp
> +  GIVEN("A circuit with classical control (3)") {
Done.

2022-09-03 12:18 UTC, lmondada commented on tket/src/Circuit/include/Circuit/CircUtils.hpp
> + * Note that this does not support recursive conditional OpTypes.
Good point. I'm now handling nesting more elegantly.

2023-08-08 08:31 UTC, closed without merging