Docs/term sequence
CQCL/tket pull request #932
Opened 2023-07-11 15:57 UTC by CalMacCQ

Updated the docstring for `gen_term_sequence_circuit`. 

Hopefully it'll be clearer what this method does now. Maybe this sort of method would be better to have in an application library going forward.

2023-07-12 08:00 UTC, willsimmons1465 requested changes
A couple of minor adjustments needed. Much better than the original though

2023-07-12 08:00 UTC, willsimmons1465 commented on pytket/pytket/utils/term_sequence.py
> +    circuit rather than minimising trotter error.
Reduces two qubit gate count _when considering applying PauliSimp or GuidedPauliSimp_. It need not minimise them for other compilation strategies.

2023-07-12 08:30 UTC, CalMacCQ commented on pytket/pytket/utils/term_sequence.py
> +    approximating :math:`e^{\\frac{\\pi}{2}\\theta P}`. This method performs
Ah yeah I forgot the imaginary unit, thanks

2023-07-12 09:47 UTC, CalMacCQ commented on pytket/pytket/utils/term_sequence.py
> +    graph colouring method.
Thanks, let me now if the revised wording is okay

2023-07-12 13:54 UTC, willsimmons1465 commented on pytket/pytket/utils/term_sequence.py
> +    graph colouring method.
Sorry, I meant in the actual API for PauliPartitionStrat: https://github.com/CQCL/tket/blob/366a0a6386112c416f11bf3493840570eeb6692f/pytket/binders/partition.cpp#L33

2023-07-12 13:55 UTC, CalMacCQ commented on pytket/pytket/utils/term_sequence.py
> +    graph colouring method.
Oh I see update the docstring for PauliPartitionStrat. Will do.

2023-07-12 13:55 UTC, willsimmons1465 commented on pytket/pytket/utils/term_sequence.py
> +    approximating :math:`e^{\\frac{\\pi}{2}\\theta P}`. This method performs
The updated version still contains the unexplained theta

2023-07-13 12:06 UTC, willsimmons1465 approved these changes
Looking good, thanks for fixing this up

2023-07-13 12:33 UTC, merged