Add kwargs to arguments for Backend.get_compiled_circuit
CQCL/tket pull request #962
Opened 2023-08-09 16:17 UTC by sjdilkes

2023-08-09 16:34 UTC, cqc-alec requested changes

2023-08-09 16:34 UTC, cqc-alec commented on pytket/pytket/backends/backend.py
> +        self.default_compilation_pass(optimisation_level, kwargs).apply(return_circuit)
```suggestion
        self.default_compilation_pass(optimisation_level, **kwargs).apply(return_circuit)
```

2023-08-10 09:07 UTC, sjdilkes commented on pytket/pytket/backends/backend.py
> +        self, optimisation_level: int = 2, **kwarfs
Now that's an embarrassing one, fixed!

2023-08-10 09:08 UTC, sjdilkes commented on pytket/pytket/backends/backend.py
> +            self.get_compiled_circuit(c, optimisation_level, kwargs) for c in circuits
done

2023-08-10 09:08 UTC, sjdilkes commented on pytket/pytket/backends/backend.py
> +        self.default_compilation_pass(optimisation_level, kwargs).apply(return_circuit)
done

2023-08-10 09:56 UTC, cqc-alec reviewed
Ah! Is this going to break all the backends?

2023-08-10 10:06 UTC, sjdilkes commented
> Ah! Is this going to break all the backends?

Yeah, they're all going need to have `**kwargs` added to their corresponding `default_compilation_pass` methods. I think it's worth it to allow users to pass backend specific optimisation choices through the usual interface, and at least any existing user code will work fine.

2023-08-10 10:12 UTC, cqc-alec commented
> > Ah! Is this going to break all the backends?
> 
> Yeah, they're all going need to have `**kwargs` added to their corresponding `default_compilation_pass` methods. I think it's worth it to allow users to pass backend specific optimisation choices through the usual interface, and at least any existing user code will work fine.

But it does mean that if someone updates pytket their code will stop working, which breaks the 1.x API promise.

We could make new `Backend` methods `get_default_compilation_pass_v2`, `get_compiled_circuit_v2` and `get_compiled_circuits_v2` which take the kwargs and call the existing methods by default, and override them in pytket-quantinuum (making the old methods call the new ones)?

2023-08-10 10:18 UTC, sjdilkes commented
> > > Ah! Is this going to break all the backends?
> > 
> > 
> > Yeah, they're all going need to have `**kwargs` added to their corresponding `default_compilation_pass` methods. I think it's worth it to allow users to pass backend specific optimisation choices through the usual interface, and at least any existing user code will work fine.
> 
> But it does mean that if someone updates pytket their code will stop working, which breaks the 1.x API promise.
> 
> We could make new `Backend` methods `get_default_compilation_pass_v2`, `get_compiled_circuit_v2` and `get_compiled_circuits_v2` which take the kwargs and call the existing methods by default, and override them in pytket-quantinuum (making the old methods call the new ones)?

Good point, I didn't think about people updating `pytket` but not the corresponding extension package.

That's a good idea - I'll do that now.

2023-08-10 10:20 UTC, sjdilkes commented
> > > > Ah! Is this going to break all the backends?
> > > 
> > > 
> > > Yeah, they're all going need to have `**kwargs` added to their corresponding `default_compilation_pass` methods. I think it's worth it to allow users to pass backend specific optimisation choices through the usual interface, and at least any existing user code will work fine.
> > 
> > 
> > But it does mean that if someone updates pytket their code will stop working, which breaks the 1.x API promise.
> > We could make new `Backend` methods `get_default_compilation_pass_v2`, `get_compiled_circuit_v2` and `get_compiled_circuits_v2` which take the kwargs and call the existing methods by default, and override them in pytket-quantinuum (making the old methods call the new ones)?
> 
> Good point, I didn't think about people updating `pytket` but not the corresponding extension package.
> 
> That's a good idea - I'll do that now.

Do you think I should also include `optimisation_level` in the kwargs?

2023-08-10 10:32 UTC, cqc-alec commented
Rethinking this whole thing...

2023-08-10 10:48 UTC, closed without merging