Feature/equality checking for boxes
CQCL/tket pull request #965
Opened 2023-08-10 21:54 UTC by yao-cqc

2023-08-14 09:38 UTC, cqc-alec requested changes
Thanks, just a few comments.

2023-08-14 09:38 UTC, cqc-alec commented on tket/src/Circuit/ToffoliBox.cpp
> +  for (; ita != a.end(); ita++) {
Could refactor this into a static helper function that's called twice with swapped arguments. Up to you.

2023-08-14 14:28 UTC, yao-cqc commented on tket/src/Circuit/Boxes.cpp
> +  std::optional<Eigen::MatrixXcd> other_m = other.get_box_unitary();
Do you mean` A_ == other.A_ and t_ == other.t_ (mod 2*pi)`?

2023-08-14 14:34 UTC, yao-cqc commented on tket/src/Circuit/Boxes.cpp
> +  std::optional<Eigen::MatrixXcd> other_m = other.get_box_unitary();
I'm not sure where to apply that `(mod 2*pi)` other than the eigenvalues.
```
A = np.asarray([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
B = np.asarray([[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
ebox1 = ExpBox(A, 2.3)
ebox2 = ExpBox(B, -2.3)
```
ebox1 and ebox2 have the same unitary but A!=B

Sorry, I might have misunderstood your comment.

2023-08-14 14:42 UTC, cqc-alec commented on tket/src/Circuit/Boxes.cpp
> +  std::optional<Eigen::MatrixXcd> other_m = other.get_box_unitary();
You're right, it isn't that simple. I suppose the criterion is that
```
t_ * A_ - other.t_ * other.A_ == n * 2 * pi * identity
```
for some integer `n`. But I am not sure about this.

2023-08-14 14:45 UTC, cqc-alec commented on tket/src/Circuit/Boxes.cpp
> +  std::optional<Eigen::MatrixXcd> other_m = other.get_box_unitary();
Happy to keep what you have.

2023-08-14 14:48 UTC, yao-cqc commented on tket/src/Circuit/Multiplexor.cpp
> +  return op_map_ == other.op_map_;
Absolutely right! Thanks

2023-08-15 07:57 UTC, cqc-alec approved these changes

2023-08-15 08:27 UTC, merged